FORMAT_ENVIRONMENT = {
    "CB_RED": "bus",
    "CB_RED_OFF": "bus",
    "LR_RED_OFF": "bus",
    "SS_RED_OFF": "bus",
    "TS_RED": "bus",
    "TS_RED_OFF": "bus",
    "TCP": "tcp",
    "TPPV": "tpp",
    "TPPV_OFF": "tpp",
    "TPPH": "tpp",
    "TPPH_OFF": "tpp",
    "NR04": "nr",
    "04": "tfl",
    "06": "tfl",
    "12": "tfl",
    "12I": "tfl",
    "04I": "tfl",
    "16": "tfl",
    "48": "tfl",
    "96": "tfl"
}
